version: "3"

services:
  test-happyx:
    build:
      context: .
      args:
        http_proxy: ${HTTP_PROXY}
    image: test-happyx
    container_name: test-happyx 
    network_mode: host # 使用 host 网络
